### ISSUE TITLE
New dataset for python open labs

### ISSUE THREAD

**Issue by clairecahoon** [ncsu-libraries-data-vis/python-open-labs#2]
We were thinking at one point about switching to a new sample dataset, what about this one? There are some numbers to work with under height and width, and there are two datasets (artworks and artists) for merging. Is there enough there for the visualization section too?

https://github.com/MuseumofModernArt/collection

**Comment by WaltGurley** [comment]
I'm okay with switching to that dataset–I think there's some good vis/analysis we could do with the aforementioned work sizes and artist metadata. If we use it we'll need to subsample the data, the artworks dataset contains over 130,000 rows, as loading the data might be an issue (it took over one minute to load the csv via github on my personal machine). If we switch datasets will that be enough lead-time for being prepared for Wed? I can create data files similar to the style we had with the FAA dataset.

**Comment by clairecahoon** [comment]
Yes, I think that's enough time! I tried some of the activities with the new dataset, and the swap is mostly changing variable names. The later workshops will take a bit more changing but I don't think it's too much.

**Comment by WaltGurley** [comment]
Datasets are created and are stored in our [Teaching Datasets repository](https://github.com/ncsu-libraries-data-vis/teaching-datasets/tree/main/moma_data). There are three datasets consisting of paintings, sculptures, and photographs and a dataset of artist info. We will reference the data from that repo

**Comment by WaltGurley** [comment]
Love the new dataset!

![image](https://c.tenor.com/S1dZOg6BqM4AAAAC/ferris-buellers-day-off-museum.gif)
